name: Deploy Github pages
on: [push]

jobs:
  deploy:
    name: Install and Build 🔧
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: Build website
        working-directory: website
        run: |
          npm install --frozen-lockfile
          npm build
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: build
